#:include '../src/common.fypp'
#:set PROGRAM_NAME = 'check_reference0'
program ${PROGRAM_NAME}$

    use, intrinsic :: iso_fortran_env, only: error_unit
#:for REAL_KIND in REAL_KINDS
    use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
#:endfor

    use, non_intrinsic :: elliptic_k_using_agm_fortran



    implicit none



    character(*), parameter :: reference_file = 'test/reference0.csv'



#:for REAL_KIND in REAL_KINDS
    call test_${REAL_KIND}$
#:endfor



    contains



    subroutine close_file(unit, stat, msg)

        integer, intent(in) :: unit

        integer, intent(out) :: stat

        character(*), intent(inout) :: msg



        close( &!
        unit   = unit , &!
        iostat = stat , &!
        iomsg  = msg    &!
        )

        call handle_stat(stat, msg)

    end subroutine close_file



    subroutine handle_stat(stat, msg)

        integer, intent(in) :: stat

        character(*), intent(in) :: msg



        if (stat .ne. 0) then

            write( unit = error_unit, fmt = '(A,I0)') 'iostat : ', stat
            write( unit = error_unit, fmt = '(A,A)' ) 'iomsg  : ', trim(msg)

            error stop

        end if

    end subroutine handle_stat



    subroutine open_reference_file(unit, stat, msg)

        integer, intent(inout) :: unit

        integer, intent(out) :: stat

        character(*), intent(inout) :: msg



        open( &!
        file    = reference_file , &!
        newunit = unit           , &!
        action  = 'read'         , &!
        status  = 'old'          , &!
        iostat  = stat           , &!
        iomsg   = msg              &!
        )

        call handle_stat(stat, msg)

    end subroutine open_reference_file
#:for REAL_KIND in REAL_KINDS



    #:set SUBROUTINE_NAME = 'test_' + REAL_KIND
    subroutine ${SUBROUTINE_NAME}$

        integer :: cnt

        integer :: file_unit

        integer :: stat

        real(${REAL_KIND}$) :: elliptic_k_cal

        real(${REAL_KIND}$) :: elliptic_k_dif

        real(${REAL_KIND}$) :: elliptic_k_ref

        real(${REAL_KIND}$) :: k

        real(${REAL_KIND}$) :: temp

        real(${REAL_KIND}$) :: ulp_error

        real(${REAL_KIND}$) :: ulp_error_abs

        character(256) :: msg



        call open_reference_file( &!
        unit = file_unit , &!
        stat = stat      , &!
        msg  = msg         &!
        )



        cnt = 0



        do

            read( &!
            unit   = file_unit , &!
            fmt    = *         , &!
            iostat = stat      , &!
            iomsg  = msg         &!
            ) &!
            k, elliptic_k_ref

            if ( is_iostat_end(stat) ) then
                exit
            else
                call handle_stat(stat, msg)
            end if

            cnt  = cnt + 1
            temp = 1.0_${REAL_KIND}$ - (k * k)

            if (temp .lt. 1.0_${REAL_KIND}$) then

                elliptic_k_cal = elliptic_k(k)
                elliptic_k_dif = elliptic_k_cal -         elliptic_k_ref
                ulp_error      = elliptic_k_dif / spacing(elliptic_k_ref)
                ulp_error_abs  = abs(ulp_error)



                if ( ulp_error_abs .gt. 2.0_${REAL_KIND}$ ) then

                    write( unit = error_unit, fmt = * ) &!
                        'WARNING: Large ULP error'

                    write( unit = error_unit, fmt = * ) &!
                        'k               = ' , k

                    write( unit = error_unit, fmt = * ) &!
                        'elliptic_k(ref) = ' ,  elliptic_k_ref

                    write( unit = error_unit, fmt = * ) &!
                        'elliptic_k(cal) = ' ,  elliptic_k_cal

                    write( unit = error_unit, fmt = * ) &!
                        'ULP error       = ' ,  ulp_error

                end if



                if ( ulp_error_abs .gt. 10.0_${REAL_KIND}$ ) then

                    write( unit = error_unit, fmt = * ) &!
                        'FAIL: Unacceptable error'

                    write( unit = error_unit, fmt = * ) &!
                        'k               = ' , k

                    write( unit = error_unit, fmt = * ) &!
                        'elliptic_k(ref) = ' ,  elliptic_k_ref

                    write( unit = error_unit, fmt = * ) &!
                        'elliptic_k(cal) = ' ,  elliptic_k_cal

                    write( unit = error_unit, fmt = * ) &!
                        'ULP error       = ' ,  ulp_error

                    error stop

                end if


            else

                cycle

            end if

        end do



        call close_file( &!
        unit = file_unit , &!
        stat = stat      , &!
        msg  = msg         &!
        )

    end subroutine ${SUBROUTINE_NAME}$
    #:del SUBROUTINE_NAME
#:endfor

end program ${PROGRAM_NAME}$
