#:include 'common.fypp'
#:set MODULE_NAME = 'elliptic_k_using_agm_fortran'
module ${MODULE_NAME}$
    !! A Fortran library for computing the complete elliptic integral of the first kind using AGM

#:for REAL_KIND in REAL_KINDS
    use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
#:endfor

    use, non_intrinsic :: arithmetic_geometric_mean_fortran



    implicit none



    private

end module ${MODULE_NAME}$
