#:include 'common.fypp'
#:set INTERFACE_NAME = 'elliptic_k'
#:set MODULE_NAME = INTERFACE_NAME + '_using_agm_fortran'
module ${MODULE_NAME}$
    !! A Fortran library for computing the complete elliptic integral of the first kind using AGM

#:for REAL_KIND in REAL_KINDS
    use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
#:endfor

    use, non_intrinsic :: arithmetic_geometric_mean_fortran



    implicit none



    private



#:set MAXVAL_LEN = 0
#:for REAL_KIND in REAL_KINDS
    #:set MAXVAL_LEN = max( MAXVAL_LEN, len(REAL_KIND) )
#:endfor
#:for REAL_KIND in REAL_KINDS
    #:set REAL_KIND_LJUST = REAL_KIND.ljust(MAXVAL_LEN)
    real( ${REAL_KIND_LJUST}$ ), parameter :: half_pi_${REAL_KIND_LJUST}$ = 1.57079632679489661923132169163975144210_${REAL_KIND}$
#:endfor
#:del MAXVAL_LEN
#:del REAL_KIND_LJUST

end module ${MODULE_NAME}$
